### ISSUE TITLE
All data in series object is plotted, regardless of the 'display' value

### ISSUE THREAD

**Issue by matsvandecavey** [arnoutaertgeerts/python-highcharts#13]
When creating a 'series' object, with display=True for a subset of variables, this value is overwritten to True for all variables in by charts.plot(series).
The dataframe.ipynb ipython notebook shows this behaviour. 
It now plots all variables, not only the ones with 'display'=True.

**Comment by arnoutaertgeerts** [comment]
@matsvandecavey I changed this behavior in the new version (0.2.0). You know have to specify which variables to plot in the `plot()` method instead of setting the display property in the dictionary. You have three options:
- `display=True`: Show all series
- `display=False`: Show no series
- `display=['variable']`: Show a subset of variables given by name.

Furthermore, you don't have to convert the dataframe to a series object anymore. You can just do:

``` python
plot(df, options, display=['A', 'Z']
```

I think you can see an example in the _Different series type_ notebook.

**Comment by matsvandecavey** [comment]
Should you then leave out the option to change the 'display' modifier in the low level df_to_series?
and/or leave out the dataframe.ipynb example?

**Comment by arnoutaertgeerts** [comment]
@matsvandecavey The function `df_to_series()` in the `data` module actually became obsolete and never has to be called by the user. It is replaced by the `df_to_series()` function in the `core` module.

Now if you want to plot a dataframe you can just do: `plot(df)`.

**Comment by arnoutaertgeerts** [comment]
I assume this is ok like this?
