### ISSUE TITLE
Can't seem to use formatter for tooltip

### ISSUE THREAD

**Issue by howe1rp** [arnoutaertgeerts/python-highcharts#35]
Greetings,

I'm trying to define a function to use in the tooltip formatter, however when I add
'tooltip': {
    'formatter': 'function() { return this.point.y; }'
}
Nothing shows up in the tooltip when I hover. It works just fine when i use pointFormat, but for some reason it doesn't work when trying to add functions.

Any help is very much appreciated!

**Comment by arnoutaertgeerts** [comment]
@howe1rp if you can provide me a complete example which reproduces the bug, I'll look into it tomorrow!

**Comment by howe1rp** [comment]
Thank you very much.

Here is a basic example:

``` python
import charts
series = [{`
    'data': [1, 2, 3, 4, 5]`
}]
options = {
    'tooltip': {
        # 'pointFormat': '{point.y}'
        'formatter': 'function() { return this.point.y; }'
    }
}
charts.plot(series, options=options, show='inline', type='line')
```

With the code the way it is, there is no tooltip, however if you comment out the formatter line and uncomment the pointFormat line it works.

**Comment by arnoutaertgeerts** [comment]
The error occurred due to the fact that you format the function as a string so javascript has no way of knowing it really is a function. However it is impossible to prevent this due to the conversion to JSON (which will convert everything into a string). I wrote a quick function which removes the string quotes from the converted JSON object and it works for your case :) I'm not sure if it will work for all functions but we will see! 

It is updated in the new version: https://github.com/arnoutaertgeerts/python-highcharts/tree/0.4.4

**Comment by howe1rp** [comment]
Fantastic! It's working now. Worth noting that if anyone wants to use quotes in the function they'll have to use single quotes.

**Comment by arnoutaertgeerts** [comment]
@howe1rp You are right! And for know I also think you cannot provide more than one function :)

**Comment by arnoutaertgeerts** [comment]
@howe1rp I changed the function handling behavior. If you want to use a javascript function in the options, you should pre and affix the statement with `@#`. The procedure is explained in [this notebook](http://nbviewer.ipython.org/github/arnoutaertgeerts/python-highcharts/blob/master/Javascript%20functions%20in%20options.ipynb).

**Comment by howe1rp** [comment]
@arnoutaertgeerts Thank you for working on this. Unfortunately, it doesn't seem to be working for me. See this example:

``` python
import charts

series = [{
    'data': [1, 2, 3, 4, 5]
}]
options = {
    'tooltip': {
        'formatter': '@#function() { return this.series.name + "<br/>" + this.point.y }@#'
    }
}
charts.plot(series, options=options, show='inline', type='line')
```

**Comment by arnoutaertgeerts** [comment]
@howe1rp Try to use double quotes for the keywords and single quotes inside the function:

``` python
import charts

series = [{
    'data': [1, 2, 3, 4, 5]
}]
options = {
    "tooltip": {
        "formatter": "@#function() { return this.series.name + '<br/>' + this.point.y }@#"
    }
}
charts.plot(series, options=options, show='inline', type='line')
```

That should do the trick. The error is due to parsing the JSON I think... If you are familiar with the chrome developer tools, you can always use them to see how the python code was transformed in javascript to find potential errors.

**Comment by howe1rp** [comment]
@arnoutaertgeerts I tried this and it looks like it's not stripping out the @# at the beginning and end.

This is how it looks:

``` js
var options = {"scale": 2, "chart": {"type": "line"}, "tooltip": {"formatter": "@#function() { return this.series.name + '<br/>' + this.point.y; }@#}, "height": 400, "width": "auto", "type": "line"}
```

**Comment by arnoutaertgeerts** [comment]
@howe1rp Did you try the github version? Or the pip version?
Op di 1 sep. 2015 om 17:32 schreef howe1rp notifications@github.com

**Comment by howe1rp** [comment]
@arnoutaertgeerts I used the pip version.

**Comment by arnoutaertgeerts** [comment]
Can you try again with version 0.4.6?

**Comment by howe1rp** [comment]
@arnoutaertgeerts It's working great now. Thank you very much!
